version = "3.10.1"

runner.dialect = scala213

preset = default
maxColumn = 120

# Preserve source newlines unless formatting needs to change
newlines.source = keep

assumeStandardLibraryStripMargin = true
includeNoParensInSelectChains = true

# Scaladoc formatting
docstrings.style = Asterisk
docstrings.wrap  = no

# Alignment
align = most
align.tokens."+" = [
  "|",
  "!",
  "!!",
  "||",
  "=>",
  "=",
  "->",
  "<-",
  "|@|",
  "//",
  "/",
  "+",
  "%",
  "%%",
  {
    code  = "="
    owner = ".*"
  }
]

continuationIndent.defnSite = 2

# Rewrite rules
rewrite.rules = [
  AsciiSortImports,
  AvoidInfix,
  PreferCurlyFors,
  RedundantBraces,
  RedundantParens,
  SortModifiers
]

project.git = true