addSbtPlugin("com.eed3si9n"              % "sbt-assembly"        % "0.15.0")
addSbtPlugin("com.eed3si9n"              % "sbt-buildinfo"       % "0.9.0")
addSbtPlugin("com.frugalmechanic"        % "fm-sbt-s3-resolver"  % "0.19.0")
addSbtPlugin("com.github.sbt"            % "sbt-dynver"          % "5.0.1")
addSbtPlugin("com.github.sbt"            % "sbt-native-packager" % "1.9.9")
addSbtPlugin("org.scalameta"             % "sbt-scalafmt"        % "2.5.0")
addSbtPlugin("org.scoverage"             % "sbt-scoverage"       % "1.9.3")
